package com.cloud.factory.net.client;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "NETWORK_REQUEST".
 */
public class NetworkRequest {

    private Long id;
    /** Not-null value. */
    private String uuid;
    /** Not-null value. */
    private String requestUrl;
    private String requestMethod;
    private String requestBody;
    private String requestContentLength;
    private String requestTime;
    private String responseBody;
    private String responseContentLength;
    private String responseStatus;
    private String responseMessage;
    private String responseTime;
    private String period;
    private String version;
    private String operateTime;

    public NetworkRequest() {
    }

    public NetworkRequest(Long id) {
        this.id = id;
    }

    public NetworkRequest(Long id, String uuid, String requestUrl, String requestMethod, String requestBody, String requestContentLength, String requestTime, String responseBody, String responseContentLength, String responseStatus, String responseMessage, String responseTime, String period, String version, String operateTime) {
        this.id = id;
        this.uuid = uuid;
        this.requestUrl = requestUrl;
        this.requestMethod = requestMethod;
        this.requestBody = requestBody;
        this.requestContentLength = requestContentLength;
        this.requestTime = requestTime;
        this.responseBody = responseBody;
        this.responseContentLength = responseContentLength;
        this.responseStatus = responseStatus;
        this.responseMessage = responseMessage;
        this.responseTime = responseTime;
        this.period = period;
        this.version = version;
        this.operateTime = operateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUuid() {
        return uuid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /** Not-null value. */
    public String getRequestUrl() {
        return requestUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl;
    }

    public String getRequestMethod() {
        return requestMethod;
    }

    public void setRequestMethod(String requestMethod) {
        this.requestMethod = requestMethod;
    }

    public String getRequestBody() {
        return requestBody;
    }

    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody;
    }

    public String getRequestContentLength() {
        return requestContentLength;
    }

    public void setRequestContentLength(String requestContentLength) {
        this.requestContentLength = requestContentLength;
    }

    public String getRequestTime() {
        return requestTime;
    }

    public void setRequestTime(String requestTime) {
        this.requestTime = requestTime;
    }

    public String getResponseBody() {
        return responseBody;
    }

    public void setResponseBody(String responseBody) {
        this.responseBody = responseBody;
    }

    public String getResponseContentLength() {
        return responseContentLength;
    }

    public void setResponseContentLength(String responseContentLength) {
        this.responseContentLength = responseContentLength;
    }

    public String getResponseStatus() {
        return responseStatus;
    }

    public void setResponseStatus(String responseStatus) {
        this.responseStatus = responseStatus;
    }

    public String getResponseMessage() {
        return responseMessage;
    }

    public void setResponseMessage(String responseMessage) {
        this.responseMessage = responseMessage;
    }

    public String getResponseTime() {
        return responseTime;
    }

    public void setResponseTime(String responseTime) {
        this.responseTime = responseTime;
    }

    public String getPeriod() {
        return period;
    }

    public void setPeriod(String period) {
        this.period = period;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getOperateTime() {
        return operateTime;
    }

    public void setOperateTime(String operateTime) {
        this.operateTime = operateTime;
    }

}
